server:
  port: 8001
spring:
  application:
    name: common-config-up2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beanzero/common-config/

learn:
  common:
    config: common-config-v1