server:
  port: 8001
spring:
  application:
    name: common-config-up1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beanzero/common-config/
#          search-paths:
#          username:
#          password: